require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SubjectStreamsController do

  # This should return the minimal set of attributes required to create a valid
  # SubjectStream. As you add validations to SubjectStream, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "subject_stream" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SubjectStreamsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all subject_streams as @subject_streams" do
      subject_stream = SubjectStream.create! valid_attributes
      get :index, {}, valid_session
      assigns(:subject_streams).should eq([subject_stream])
    end
  end

  describe "GET show" do
    it "assigns the requested subject_stream as @subject_stream" do
      subject_stream = SubjectStream.create! valid_attributes
      get :show, {:id => subject_stream.to_param}, valid_session
      assigns(:subject_stream).should eq(subject_stream)
    end
  end

  describe "GET new" do
    it "assigns a new subject_stream as @subject_stream" do
      get :new, {}, valid_session
      assigns(:subject_stream).should be_a_new(SubjectStream)
    end
  end

  describe "GET edit" do
    it "assigns the requested subject_stream as @subject_stream" do
      subject_stream = SubjectStream.create! valid_attributes
      get :edit, {:id => subject_stream.to_param}, valid_session
      assigns(:subject_stream).should eq(subject_stream)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SubjectStream" do
        expect {
          post :create, {:subject_stream => valid_attributes}, valid_session
        }.to change(SubjectStream, :count).by(1)
      end

      it "assigns a newly created subject_stream as @subject_stream" do
        post :create, {:subject_stream => valid_attributes}, valid_session
        assigns(:subject_stream).should be_a(SubjectStream)
        assigns(:subject_stream).should be_persisted
      end

      it "redirects to the created subject_stream" do
        post :create, {:subject_stream => valid_attributes}, valid_session
        response.should redirect_to(SubjectStream.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved subject_stream as @subject_stream" do
        # Trigger the behavior that occurs when invalid params are submitted
        SubjectStream.any_instance.stub(:save).and_return(false)
        post :create, {:subject_stream => { "subject_stream" => "invalid value" }}, valid_session
        assigns(:subject_stream).should be_a_new(SubjectStream)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SubjectStream.any_instance.stub(:save).and_return(false)
        post :create, {:subject_stream => { "subject_stream" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested subject_stream" do
        subject_stream = SubjectStream.create! valid_attributes
        # Assuming there are no other subject_streams in the database, this
        # specifies that the SubjectStream created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SubjectStream.any_instance.should_receive(:update).with({ "subject_stream" => "MyString" })
        put :update, {:id => subject_stream.to_param, :subject_stream => { "subject_stream" => "MyString" }}, valid_session
      end

      it "assigns the requested subject_stream as @subject_stream" do
        subject_stream = SubjectStream.create! valid_attributes
        put :update, {:id => subject_stream.to_param, :subject_stream => valid_attributes}, valid_session
        assigns(:subject_stream).should eq(subject_stream)
      end

      it "redirects to the subject_stream" do
        subject_stream = SubjectStream.create! valid_attributes
        put :update, {:id => subject_stream.to_param, :subject_stream => valid_attributes}, valid_session
        response.should redirect_to(subject_stream)
      end
    end

    describe "with invalid params" do
      it "assigns the subject_stream as @subject_stream" do
        subject_stream = SubjectStream.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SubjectStream.any_instance.stub(:save).and_return(false)
        put :update, {:id => subject_stream.to_param, :subject_stream => { "subject_stream" => "invalid value" }}, valid_session
        assigns(:subject_stream).should eq(subject_stream)
      end

      it "re-renders the 'edit' template" do
        subject_stream = SubjectStream.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SubjectStream.any_instance.stub(:save).and_return(false)
        put :update, {:id => subject_stream.to_param, :subject_stream => { "subject_stream" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested subject_stream" do
      subject_stream = SubjectStream.create! valid_attributes
      expect {
        delete :destroy, {:id => subject_stream.to_param}, valid_session
      }.to change(SubjectStream, :count).by(-1)
    end

    it "redirects to the subject_streams list" do
      subject_stream = SubjectStream.create! valid_attributes
      delete :destroy, {:id => subject_stream.to_param}, valid_session
      response.should redirect_to(subject_streams_url)
    end
  end

end
